export const algorithms = [
  {
    code: 'A1',
    name: 'Precision Adder',
    Z: 'Offset (CV)',
    X: 'Input',
    Y: 'Input',
    A: 'X+Y+Z',
    B: 'X-Y-Z',
    extra: ['knob_recorder'],
    description: `
      <p>Output A is the sum of inputs X & Y; output B is the difference between inputs X & Y. With nothing plugged into input X, B is therefore simply an inverted copy of Y.</p>
      <p>The Z knob/CV sets an offset which is applied to both A and B. The offset is a whole number of Volts. If X/Y are 1V/Octave pitch CVs, Z is therefore an octave shift control. The maximum shift is 10V, positive or negative.</p>
      <p>When Z changes, the offset is shown on the display. After a short while the display reverts to showing the current algorithm.</p>
    `,
    video: 'https://www.youtube.com/watch?v=mCFaTt6vNpk',
    parameters: [
      {
        min: 0,
        max: 1,
        default: 0,
        description: 'When 1, the offset is not restricted to 1V steps, and changes smoothly with Z.',
      },
    ],
  },
  {
    code: 'A2',
    name: 'Four Quadrant Multiplier',
    Z: 'Scale',
    X: 'Input',
    Y: 'Input',
    A: 'X*Y*Z',
    B: '-X*Y*Z',
    extra: ['knob_recorder'],
    description: `
      <p>Output A is the result of multiplying inputs X & Y. Output B is the inverse of output A.</p>
      <p>If for example X is a signal and Y is an envelope, then this algorithm is a VCA. If both inputs are signals, then this is a ring modulator.</p>
      <p>The Z knob/CV sets a scale factor which is applied to both outputs. The scale is an integer (whole number) which either multiplies or divides the result, and ranges in value from 1-10.</p>
      <p>When Z changes, the scale is shown on the display. If the value shown is negative, it is a divisor rather than a multipler. Note that there is no value of "-1" since dividing by 1 and multiplying by 1 are the same. After a short while the display reverts to showing the current algorithm.</p>
    `,
    video: 'https://www.youtube.com/watch?v=nRBbdbQZi5Q',
    parameters: [
      {
        min: 0,
        max: 1,
        default: 0,
        description: 'When 1, the scale is not restricted to integer steps, and changes smoothly with Z.',
      },
    ],
  },
  {
    code: 'A3',
    name: 'Full-wave Rectifier',
    Z: 'Select Mode',
    X: 'Input',
    Y: 'Input',
    A: 'abs(X+Y) / abs(X)',
    B: 'abs(X-Y) / abs(Y)',
    extra: [],
    description: `
      <p>This algorithm provides a full-wave rectifier or absolute value function. The Z knob/CV select between one of two modes. In 'independent' mode, A and B are the absolute values of X and Y, respectively. In 'combined' mode, A is the absolute value of the sum of X & Y; B is the absolute value of the difference of X & Y.</p>
      <p>When Z changes, the mode is displayed. 'Independent' mode is shown as "-0"; 'combined' mode as "0". After a short while the display reverts to showing the current algorithm.</p>
    `,
    video: 'https://www.youtube.com/watch?v=DA1rK1S6wuo',
    parameters: [],
  },
  {
    code: 'A4',
    name: 'Minimum/maximum',
    Z: 'Gate',
    X: 'Input',
    Y: 'Input',
    A: 'min(X,Y)',
    B: 'max(X,Y)',
    extra: [],
    description: `
      <p>Output A is the minimum of inputs X & Y; output B is the maximum of the two inputs. If one input is zero (or disconnected), this is a half-wave rectifier.</p>
      <p>The Z knob/CV provides a gate function. When Z goes higher than approximately 2.5V, the gate goes high and the outputs follow the inputs according to the min/max relationship. When Z goes below approximately -1.5V, the gate goes low and the outputs are frozen.</p>
      <p>When the gate changes state, "LO" or "HI" is displayed to indicate the gate status. After a short while the display reverts to showing the current algorithm.</p>
    `,
    video: 'https://www.youtube.com/watch?v=GpkaOchvVSE',
    parameters: [],
  },
  {
    code: 'A5',
    name: 'Linear/Exponential Converter',
    Z: 'Tune',
    X: 'Exp In',
    Y: 'Linear In',
    A: 'Linear Out',
    B: 'Exp Out',
    extra: [],
    description: `
      <p>This algorithm provides a linear-to-exponential converter and an exponential-to-linear converter. You might use this to interface 1V/octave modules (Eurorack standard) with Hz/V synths (e.g. old Korg or Yamaha synths), but it could also be useful within Eurorack e.g. to convert an LFO (commonly with Hz/V pitch control) to a V/octave oscillator, or to convert an exponential FM input on a VCO into a linear FM input.</p>
      <p>Input X is the exponential input; its corresponding linear output is A. Y is the linear input, whose exponential output is B.</p>
      <p>Z sets the scale factor which is common to both conversions. It sets the number of Hz per Volt, with arrange from near zero to about 2kHz. The Yamaha CS-15, for example, uses about 1100Hz/V, which is about half way on the Z knob here.</p>
      <p>The zero Volt point on the exponential scale used is C3 (approximately 130.81Hz).</p>
    `,
    video: 'https://www.youtube.com/watch?v=jpnlxEnd1Lw',
    parameters: [],
  },
  {
    code: 'A6',
    name: 'Quantizer',
    Z: 'Scale & Mode',
    X: 'Input',
    Y: 'Transpose / Trigger In',
    A: 'Quantized',
    B: 'Trigger',
    extra: ['midi_support'],
    description: `
      <p>Output A is a quantized version of input X; the closest whole-semitone value to the unquantized V/octave pitch CV X. Output B is a trigger signal which fires whenever output A changes - a 5V pulse approximately 10ms long.</p>
      <p>As well as providing a chromatic scale, this algorithm can also constrain the quantized values to a musical scale or chord. This is controlled by the Z knob/CV.</p>
      <p>When Z changes, the scale is displayed on the LEDs. The scale's number in the following table is show, and after a short pause, the scale's name. After the name has scrolled across, the display reverts to showing the current algorithm.</p>
      <table>
        <thead>
          <tr>
            <td>Number</td>
            <td>Scale</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0</td>
            <td>chromatic</td>
          </tr>
          <tr>
            <td>1</td>
            <td>major scale</td>
          </tr>
          <tr>
            <td>2</td>
            <td>minor scale</td>
          </tr>
          <tr>
            <td>3</td>
            <td>major triad</td>
          </tr>
          <tr>
            <td>4</td>
            <td>minor triad</td>
          </tr>
          <tr>
            <td>5</td>
            <td>root+5th</td>
          </tr>
          <tr>
            <td>6</td>
            <td>major triad+6th</td>
          </tr>
          <tr>
            <td>7</td>
            <td>minor triad+6th</td>
          </tr>
          <tr>
            <td>8</td>
            <td>major triad+7th</td>
          </tr>
          <tr>
            <td>9</td>
            <td>minor triad+7th</td>
          </tr>
          <tr>
            <td>10</td>
            <td>root+5th+6th</td>
          </tr>
          <tr>
            <td>11</td>
            <td>root+5th+7th</td>
          </tr>
          <tr>
            <td>12</td>
            <td>pentatonic major</td>
          </tr>
          <tr>
            <td>13</td>
            <td>pentatonic minor</td>
          </tr>
          <tr>
            <td>14</td>
            <td>natural minor scale</td>
          </tr>
          <tr>
            <td>15</td>
            <td>harmonic minor scale</td>
          </tr>
        </tbody>
      </table>
      <p>A further option is controlled by Z being positive or negative. When Z is negative, the scale number is shown as a negative value.</p>
      <p><strong>When Z is positive</strong> input Y is a transpose control. The CV on input Y is quantized (to a chromatic scale) and added to the quantized result in one of two ways, controlled by parameter 1. If parameter 1 is zero, the transposition is applied to output A, after input X has been quantized to the chosen scale. If parameter 1 is one, the transposition is applied to input X before it is forced into the chosen scale. So, in mode zero the overall key of the quantization is transposed, whereas in mode one the transposition moves the notes around within the same key.</p>
      <p><strong>When Z is negative</strong> input Y is a trigger. In this mode, input X is only sampled and converted to a new quantized value when input Y rises over approximately 1V. (In non-triggered mode, X is constantly sampled and a new note is output as soon as X moves into the next semitone range.)</p>
      <p>Parameter 2 sets the root key of the chosen scale. At zero, the first note of the scale (e.g. C in the key of C) corresponds to 0V. If the parameter is set for example to 2, the first note of the scale is at 2/12 = 0.1667V - or to look at it another way, if your VCO is tuned so that 0V gives you a C, the quantizer is now working in the key of D (D major, minor, triad etc. depending on the scale setting).</p>
      <p>Parameter 3 sets an offset between the timing of the X & Y inputs (in sample frames). When using Y as a trigger, it is often a good idea to delay it slightly relative to the pitch, to ensure that the pitch has changed and settled before the trigger samples a new note.</p>
      <p><strong>MIDI Output:</strong> each new note (i.e. when the Output B trigger fires) is output as a MIDI note message on the MIDI channel selected in the settings.</p>
      <p><strong>MIDI Input:</strong> MIDI note messages received on MIDI channel 1 set parameter 2 (root key).</p>
    `,
    video: 'https://www.youtube.com/watch?v=5THsGKn3Pwk',
    parameters: [
      {
        min: -1,
        max: 31,
        default: 31,
        description: 'Input X attenuation',
      },
      {
        min: 0,
        max: 1,
        default: 0,
        description: 'Transpose mode',
      },
      {
        min: -31,
        max: 31,
        default: 0,
        description: 'Key',
      },
      {
        min: 0,
        max: 31,
        default: 0,
        description: 'Offset',
      },
    ],
  },
  {
    code: 'A7',
    name: 'Comparator',
    Z: 'Hysteresis',
    X: 'Input',
    Y: 'Input',
    A: 'X>Y',
    B: 'X<Y',
    extra: [],
    description: `
      <p>Output A is a gate signal (zero or +5V), high when input X has a higher voltage than input Y. Output B is an inverted copy of A (i.e. +5V when A is 0V and vice versa.)</p>
      <p>The Z knob/CV input sets the hysteresis (for an explanation of hysteresis see <a href="https://en.wikipedia.org/wiki/Hysteresis#Electronic_circuits">here</a>). Inputs of approximately 0-4V correspond to hysteresis values of approximately 0-10V. Negative values are clamped at zero.</p>
    `,
    video: 'https://www.youtube.com/watch?v=Ttp7RCtofg0',
    parameters: [],
  },
  {
    code: 'A8',
    name: 'Dual Waveshaper',
    Z: 'Gain',
    X: 'Input',
    Y: 'Input',
    A: 'Folded X',
    B: 'Shaped Y',
    extra: ['knob_recorder'],
    description: `
      <p>This algorithm provides two independent waveshaping functions. The Z knob/CV is a gain control, with a range of approximately 30x. Negative values of Z invert the signal.</p>
      <p>Input X/output A provide what is usually termed a wavefolder. This increases the harmonic content of the sound in interesting ways, especially as the gain changes.</p>
      <p>Input Y/output B provide a triangle-to-sine waveshaper. Used on most audio this is a relatively gentle form of overdrive/saturation. However, when fed with the right level of triangle wave, the output is exactly a sine wave, which is useful when you have a triangle wave VCO handy but really want a pure sine wave instead.</p>
    `,
    video: 'https://www.youtube.com/watch?v=-B1VzxQ2qOo',
    parameters: [],
  },
  {
    code: 'B1',
    name: 'Sample and Hold',
    Z: 'Slew rate',
    X: 'Input',
    Y: 'Trigger',
    A: 'Sampled X',
    B: 'Noise',
    extra: ['z_trigger'],
    description: `
      <p><strong>If parameter 0 is 0 (the default):</strong></p>
      <p>Output A is a sample of input X, taken when the trigger input Y goes over 1V. (Sample and Hold)</p>
      <p><strong>If parameter 0 is 1:</strong></p>
      <p>Output A follows input X while input Y is over 1V. When Y falls below 0.5V, output A is held until Y goes over 1V again. (Track and Hold)</p>
      <p>Output B is a white noise signal, with range ±8V. A noise signal is commonly fed into the input of a sample and hold device to generate clocked random voltages.</p>
      <p>The Z knob/CV controls the slew rate of output A. At the minimum value of Z, changes in A are instantaneous. As Z increases, changes in A take place more slowly.</p>
    `,
    video: 'https://www.youtube.com/watch?v=x8yDMQqE-yA',
    parameters: [
      {
        min: 0,
        max: 1,
        default: 0,
        description: 'Mode',
      },
    ],
  },
  {
    code: 'B2',
    name: 'Slew Rate Limiter',
    Z: 'Slew rate',
    X: 'Input',
    Y: 'Input',
    A: 'Linear slew',
    B: 'Log slew',
    extra: [],
    description: `
      <p>Outputs A & B are both slew rate limited copies of the sum of X & Y. Output A uses linear slew rate limiting; a step change in the input will typically result in a ramp output, until the output reaches its desired value, at which point it will be constant. Output B uses logarithmic slew rate limiting; a step change in input results in a smooth curve that gradually approaches the desired value.</p>
      <p>The Z knob/CV controls the slew rate for both outputs. At the minimum value of Z, changes are very rapid. As Z increases, changes take place more slowly.</p>
    `,
    video: 'https://www.youtube.com/watch?v=irKcEJCB0FQ',
    parameters: [],
  },
  {
    code: 'B3',
    name: 'Pitch and Envelope Tracker',
    Z: 'Slew rate',
    X: 'Audio In',
    Y: 'Offset A',
    A: 'V/Octave',
    B: 'Envelope',
    extra: [],
    description: `
      <p>This algorithm provides pitch and envelope tracking of an incoming audio signal. It will track frequencies down to about 27Hz, which is just below the lowest note on a standard 88 key piano.</p>
      <p>Output A is a 1V/octave pitch CV reflecting the pitch of the signal on input X. The 0V point is C3 (approximately 130.81Hz). Input Y is simply added to the pitch CV, providing a means of applying e.g. vibrato, or transposition.</p>
      <p>Output B tracks the envelope of the signal on input X. It goes to zero when the algorithm fails to track a pitch.</p>
      <p>Knob/CV Z sets the slew rate of the envelope, controlling how quickly it tracks changes in level. At the minimum value of Z, changes can be very rapid, which may produce undesirable effects, especially if pitch tracking is not working well. As Z increases, changes take place more slowly.</p>
    `,
    video: 'https://www.youtube.com/watch?v=YAlBBzNbbdg',
    parameters: [],
  },
  {
    code: 'B4',
    name: 'Clockable Delay/Echo',
    Z: 'Feedback',
    X: 'Audio In',
    Y: 'Clock',
    A: 'Dry+delay',
    B: 'Delay only',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Gj69fn-liYs',
    parameters: [
      {
        min: -15,
        max: 8,
        default: 0,
        description: 'Delay time multiplier',
      },
      {
        min: 0,
        max: 2,
        default: 0,
        description: 'Output mode',
      },
    ],
    keywords: 'effect',
  },
  {
    code: 'B5',
    name: 'LFO',
    Z: 'Tune',
    X: 'Hz/V In',
    Y: 'Waveshape',
    A: 'Saw/Sin/Tri',
    B: 'Square',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=iBtg8CJtC1E',
    parameters: [],
  },
  {
    code: 'B6',
    name: 'Clockable LFO',
    Z: 'Multiplier',
    X: 'Clock',
    Y: 'Waveshape',
    A: 'Saw/Sin/Tri',
    B: 'Square',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=_ZqZtVd8eLI',
    parameters: [],
  },
  {
    code: 'B7',
    name: 'VCO with linear FM',
    Z: 'Tune',
    X: 'V/Octave',
    Y: 'Linear FM',
    A: 'Sine',
    B: 'Saw',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=5JPUuaPaxxo',
    parameters: [],
  },
  {
    code: 'B8',
    name: 'VCO with waveshaping',
    Z: 'Tune',
    X: 'V/Octave',
    Y: 'Waveshape',
    A: 'Saw/Tri/Saw',
    B: 'Square',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=8JDX9bjcG3o',
    parameters: [],
  },
  {
    code: 'C1',
    name: 'Precision Adder (fractional offsets)',
    Z: 'Offset',
    X: 'Input',
    Y: 'Input',
    A: 'X+Y+Z',
    B: 'X-Y-Z',
    extra: ['knob_recorder'],
    description: ``,
    video: '',
    parameters: [],
  },
  {
    code: 'C2',
    name: 'Voltage Controlled Delay Line',
    Z: 'Feedback',
    X: 'Audio In',
    Y: 'Delay Time',
    A: 'Delay only',
    B: 'Dry+delay',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=xirCtbaCRUA',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'C3',
    name: 'Clockable Ping Pong Delay (Z feedback) ',
    Z: 'Feedback',
    X: 'Audio In',
    Y: 'Clock',
    A: 'Left',
    B: 'Right',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=3pHSGoLNGuQ',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'C4',
    name: 'Clockable Ping Pong Delay (Z input pan) ',
    Z: 'Input Pan',
    X: 'Audio In',
    Y: 'Clock',
    A: 'Left',
    B: 'Right',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=WdUGXBpLFt4',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'C5',
    name: 'Resonator',
    Z: 'Gain',
    X: 'Audio In',
    Y: 'V/Octave',
    A: 'Audio Out',
    B: 'Envelope',
    extra: ['z_trigger'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=uqnreY1yVd8',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'C6',
    name: 'Vocoder',
    Z: 'Decay',
    X: 'Modulator',
    Y: 'Carrier',
    A: 'Audio Out',
    B: 'Envelope',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=bYlP8Q03Xl4',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'C7',
    name: 'Phaser',
    Z: 'Feedback',
    X: 'Audio In',
    Y: 'Sweep',
    A: 'Dry+phase',
    B: 'Phase only',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=XLxi45ONXVA',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'C8',
    name: 'Bit Crusher',
    Z: 'Bit depth',
    X: 'Input',
    Y: 'Sample rate',
    A: 'Output',
    B: 'Comparator',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Tv5c8gPYwFs',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'D2',
    name: 'Tape Delay',
    Z: 'Feedback',
    X: 'Audio In',
    Y: 'Tape speed',
    A: 'Dry+delay',
    B: 'Delay only',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=yvoYk0w1Loo',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'D3',
    name: 'Waveform Animator',
    Z: 'Separation',
    X: 'Input',
    Y: 'Threshold',
    A: 'Output',
    B: 'Squarewave Output',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=htkdsLm0oa8',
    parameters: [],
  },
  {
    code: 'D4',
    name: 'State Variable Filter',
    Z: 'Filter Type',
    X: 'Audio In',
    Y: 'V/Octave',
    A: 'LP/BP/HP',
    B: 'HP/BP/LP',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=7sIsahePBHA',
    parameters: [],
  },
  {
    code: 'D5',
    name: 'LP/HP Filter',
    Z: 'Resonance',
    X: 'Audio In',
    Y: 'V/Octave',
    A: 'Low Pass',
    B: 'High pass',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=RwRScmH7atc',
    parameters: [],
  },
  {
    code: 'D6',
    name: 'LP/BP Filter',
    Z: 'Resonance',
    X: 'Audio In',
    Y: 'V/Octave',
    A: 'Low Pass',
    B: 'Band pass',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=SjmzSA3bYgc',
    parameters: [],
  },
  {
    code: 'D7',
    name: 'BP/HP Filter',
    Z: 'Resonance',
    X: 'Audio In',
    Y: 'V/Octave',
    A: 'Band pass',
    B: 'High pass',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=I9FoVhLcMPs',
    parameters: [],
  },
  {
    code: 'D8',
    name: 'BP/Notch Filter',
    Z: 'Resonance',
    X: 'Audio In',
    Y: 'V/Octave',
    A: 'Band pass',
    B: 'Notch',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Lv6r94IeERA',
    parameters: [],
  },
  {
    code: 'E1',
    name: 'AR Envelope',
    Z: 'Times',
    X: 'Trigger',
    Y: 'Trigger',
    A: 'Env Out',
    B: 'Env Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=CCae5gjnfrc',
    parameters: [],
  },
  {
    code: 'E2',
    name: 'AR Envelope (with push)',
    Z: 'Times',
    X: 'Trigger',
    Y: 'Trigger',
    A: 'Env Out',
    B: 'Env Out',
    extra: ['z_trigger'],
    description: ``,
    video: '',
    parameters: [],
  },
  {
    code: 'E3',
    name: 'AR Envelope & VCA',
    Z: 'Times',
    X: 'Trigger',
    Y: 'VCA In',
    A: 'Env Out',
    B: 'VCA Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=mC7AxLqseVc',
    parameters: [],
  },
  {
    code: 'E4',
    name: 'AR Envelope & VCA (with push)',
    Z: 'Times',
    X: 'Trigger',
    Y: 'VCA In',
    A: 'Env Out',
    B: 'VCA Out',
    extra: ['z_trigger'],
    description: ``,
    video: '',
    parameters: [],
  },
  {
    code: 'E5',
    name: 'Dual AR Envelope',
    Z: 'Times',
    X: 'Trigger A',
    Y: 'Trigger B',
    A: 'Env Out A',
    B: 'Env Out B',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=xnTesaYXU7Y',
    parameters: [],
  },
  {
    code: 'E6',
    name: 'Dual AR Envelope (with push)',
    Z: 'Times',
    X: 'Trigger A',
    Y: 'Trigger N',
    A: 'Env Out A',
    B: 'Env Out B',
    extra: ['z_trigger'],
    description: ``,
    video: '',
    parameters: [],
  },
  {
    code: 'E7',
    name: 'Euro to Buchla Converter',
    Z: 'Tune',
    X: '1V/Oct',
    Y: 'Gate',
    A: '1.2V/Oct',
    B: 'Gate/trigger',
    extra: [],
    description: ``,
    video: '',
    parameters: [],
  },
  {
    code: 'E8',
    name: 'Buchla to Euro Converter',
    Z: 'Tune',
    X: '1.2V/Oct',
    Y: 'Gate/trigger',
    A: '1V/Oct',
    B: 'Trigger',
    extra: [],
    description: ``,
    video: '',
    parameters: [],
  },
  {
    code: 'F1',
    name: 'Clockable AD Envelope (with mute)',
    Z: 'Shape',
    X: 'Clock',
    Y: 'Mute',
    A: 'Env Out',
    B: 'Env Out',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=LlM3GRI10Hk',
    parameters: [],
  },
  {
    code: 'F2',
    name: 'Clockable AD Envelope (with gate)',
    Z: 'Shape',
    X: 'Clock',
    Y: 'Gate',
    A: 'Env Out',
    B: 'Env Out',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=7H4rT9ClRFI',
    parameters: [],
  },
  {
    code: 'F3',
    name: 'Clockable AD Envelope (with trigger). ',
    Z: 'Shape',
    X: 'Clock',
    Y: 'Trigger',
    A: 'Env Out',
    B: 'Env Out',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=xQ4dGCsA1eo',
    parameters: [],
  },
  {
    code: 'F4',
    name: 'Clockable AD Envelope & VCA',
    Z: 'Shape',
    X: 'Clock',
    Y: 'VCA In',
    A: 'Env Out',
    B: 'VCA Out',
    extra: ['tap_tempo'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=rl5xEyjxXvk',
    parameters: [],
  },
  {
    code: 'F5',
    name: 'Shift Register Random CVs',
    Z: 'Randomness',
    X: 'Clock',
    Y: 'Modify',
    A: 'Unipolar',
    B: 'Bipolar',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=3sSr0X3vaDI',
    parameters: [],
  },
  {
    code: 'F6',
    name: 'Shift Register Random Quantized CVs',
    Z: 'Randomness',
    X: 'Clock',
    Y: 'Modify',
    A: 'Quantized',
    B: 'Trigger',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=hDI8juYrebw',
    parameters: [],
  },
  {
    code: 'F7',
    name: 'Shift Register Random Triggers',
    Z: 'Randomness',
    X: 'Clock',
    Y: 'Modify',
    A: 'Trigger',
    B: 'Inverse',
    extra: ['z_trigger'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=4HqIG_Brzxg',
    parameters: [],
  },
  {
    code: 'F8',
    name: 'Shift Register Random Dual Triggers',
    Z: 'Randomness',
    X: 'Clock',
    Y: 'Modify',
    A: 'Trigger A',
    B: 'Trigger B',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=b3gnEJikp9M',
    parameters: [],
  },
  {
    code: 'G1',
    name: 'E-S-1 Emulation',
    Z: 'Trim',
    X: 'Input 1',
    Y: 'Input 2',
    A: 'Output 1',
    B: 'Output 2',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=9_raPvdIMRE',
    parameters: [],
    keywords: 'utility',
  },
  {
    code: 'G2',
    name: 'E-S-2 Emulation',
    Z: 'Trim',
    X: 'Input 1',
    Y: 'Input 2',
    A: 'Output 1',
    B: 'Output 2',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=8EIPFZwQ9uQ',
    parameters: [],
    keywords: 'utility',
  },
  {
    code: 'G3',
    name: 'Pitch Reference',
    Z: 'Amplitude',
    X: '',
    Y: '',
    A: 'Sine Out',
    B: 'Square Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=MID1aSrWX7o',
    parameters: [],
    keywords: 'utility',
  },
  {
    code: 'G4',
    name: 'Frequency Reference',
    Z: 'Amplitude',
    X: '',
    Y: '',
    A: 'Sine Out',
    B: 'Square Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=fVyjM50GKWg',
    parameters: [],
    keywords: 'utility',
  },
  {
    code: 'G5',
    name: 'Tuner',
    Z: 'Amplitude',
    X: 'Input',
    Y: '',
    A: 'Output',
    B: 'Sine Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=6zXS3RKR3xw',
    parameters: [],
    keywords: 'utility',
  },
  {
    code: 'G6',
    name: 'MIDI Clock',
    Z: 'Unused',
    X: 'Clock',
    Y: 'Run/stop',
    A: 'Output',
    B: 'Output',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=af6eHIYT2Ww',
    parameters: [],
  },
  {
    code: 'G7',
    name: 'MIDI/CV',
    Z: 'Unused',
    X: 'Unused',
    Y: 'Unused',
    A: 'Pitch CV',
    B: 'Gate',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=1ArqOPnezdo',
    parameters: [],
  },
  {
    code: 'G8',
    name: 'CV/MIDI',
    Z: 'Mod or Vel',
    X: 'Pitch CV',
    Y: 'Gate',
    A: 'Unused',
    B: 'Unused',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=JLomApKB30E',
    parameters: [],
  },
  {
    code: 'H1',
    name: 'Crossfade/Pan',
    Z: 'Fade/pan',
    X: 'Input 1',
    Y: 'Input 2',
    A: 'Left Out',
    B: 'Right Out',
    extra: ['knob_recorder'],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Ar7Gym6SOSE',
    parameters: [],
  },
  {
    code: 'H2',
    name: 'Dual Sample and Hold',
    Z: 'Gate',
    X: 'Input A',
    Y: 'Input B',
    A: 'Output X',
    B: 'Output Y',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=d-kA1a9zrx8',
    parameters: [],
  },
  {
    code: 'H3',
    name: 'Dual Quantizer (Z scale)',
    Z: 'Scale',
    X: 'Input A',
    Y: 'Input B',
    A: 'Quantized X',
    B: 'Quantized Y',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=QkiZ__Kx1EE',
    parameters: [],
  },
  {
    code: 'H4',
    name: 'Dual Quantizer',
    Z: 'Trigger',
    X: 'Input A',
    Y: 'Input B',
    A: 'Quantized X',
    B: 'Quantized Y',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Ui3mC0rQ4KU',
    parameters: [],
  },
  {
    code: 'H5',
    name: 'Dual Euclidean Patterns',
    Z: 'Pulses 2',
    X: 'Clock',
    Y: 'Reset',
    A: 'Output 1',
    B: 'Output 2',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Y3E8XvoLLzg',
    parameters: [],
  },
  {
    code: 'H6',
    name: 'Dual Delayed Pulse Generator',
    Z: 'Control',
    X: 'Trigger A',
    Y: 'Trigger B',
    A: 'Output X',
    B: 'Output Y',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=7UW7IQYfFyQ',
    parameters: [],
  },
  {
    code: 'H7',
    name: 'Noise',
    Z: 'Blend Noise',
    X: 'VCA A',
    Y: 'VCA B',
    A: 'Output 1',
    B: 'Output 2',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=WBX-4gOPX50',
    parameters: [],
  },
  {
    code: 'I1',
    name: 'Audio Playback',
    Z: 'Select',
    X: 'Retrigger',
    Y: 'Start Pos',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=JAM5U5NFS1c',
    parameters: [],
  },
  {
    code: 'I2',
    name: 'Clocked Audio Playback',
    Z: 'Select',
    X: 'Retrigger',
    Y: 'Clock',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=9wZHqDfXvGg',
    parameters: [],
  },
  {
    code: 'I3',
    name: 'Audio Playback with V/Oct',
    Z: 'Select',
    X: 'Retrigger',
    Y: 'V/Oct',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=djuLLK1pZgk',
    parameters: [],
  },
  {
    code: 'I4',
    name: 'Audio Playback with Z Speed',
    Z: 'Select',
    X: 'Retrigger',
    Y: 'Start Pos',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=UG0bWiCYbsA',
    parameters: [],
  },
  {
    code: 'I5',
    name: 'Audio Playback with Reverse',
    Z: 'Speed',
    X: 'Retrigger',
    Y: 'Select',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Bft6YD6e91Q',
    parameters: [],
  },
  {
    code: 'I6',
    name: 'Audio Playback with Scrub',
    Z: 'Select',
    X: 'Unused',
    Y: 'Position',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=-Z3v_W-s2rI',
    parameters: [],
  },
  {
    code: 'I7',
    name: 'Dual Audio Playback',
    Z: 'Select',
    X: 'Trigger A',
    Y: 'Trigger B',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=tBC_KhffiGk',
    parameters: [],
  },
  {
    code: 'I8',
    name: 'Dual Audio Playback with Z Speed',
    Z: 'Speed',
    X: 'Trigger A',
    Y: 'Trigger B',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=NIt7VFPQwaw',
    parameters: [],
  },
  {
    code: 'J1',
    name: 'MIDI File Playback (Clocked)',
    Z: 'Select',
    X: 'Clock',
    Y: 'Retrigger',
    A: 'CV Out',
    B: 'Gate Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=HmQVkyjWtJE',
    parameters: [],
  },
  {
    code: 'J3',
    name: 'MIDI File Playback (Free Running)',
    Z: 'Speed',
    X: 'V/Octave',
    Y: 'Retrigger',
    A: 'CV Out',
    B: 'Gate Out',
    extra: [],
    description: ``,
    video: '',
    parameters: [],
  },
  {
    code: 'J4',
    name: 'Audio Playback with End CV',
    Z: 'Trigger/End Pos',
    X: 'End Pos/Trigger',
    Y: 'Start Pos',
    A: 'Left Out',
    B: 'Right Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=80pRG39kqlA',
    parameters: [],
  },
  {
    code: 'J5',
    name: 'Audio Recorder',
    Z: 'Record',
    X: 'Input L',
    Y: 'Input R',
    A: 'Output L',
    B: 'Output R',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=yzVoSIUWMJ0',
    parameters: [],
  },
  {
    code: 'K1',
    name: 'Wavetable VCO',
    Z: 'Tune',
    X: 'V/Octave',
    Y: 'Wave',
    A: 'Wave Out',
    B: 'Sub Out',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=piNLUIcoEoI',
    parameters: [],
  },
  {
    code: 'K5',
    name: 'Programmable Quantizer',
    Z: 'Slew',
    X: 'Input',
    Y: 'Input',
    A: 'Quantized X+Y',
    B: 'Trigger',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=fCVvjwelGU8',
    parameters: [],
  },
  {
    code: 'L1',
    name: 'Stereo Reverb',
    Z: 'Wet/Dry',
    X: 'Left Input',
    Y: 'Right Input',
    A: 'Left Output',
    B: 'Right Output',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=mF5mmdAhE30',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'L2',
    name: 'Mono-to-Stereo Reverb',
    Z: 'Wet/Dry',
    X: 'Input',
    Y: 'Feedback',
    A: 'Left Output',
    B: 'Right Output',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=mF5mmdAhE30',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'L3',
    name: 'Dual Reverb',
    Z: 'Wet/Dry',
    X: 'Input',
    Y: 'Input',
    A: 'X+Reverb',
    B: 'Y+Reverb',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=mF5mmdAhE30',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'L5',
    name: 'Stereo Chorus',
    Z: 'Wet/Dry',
    X: 'Input',
    Y: 'LFO Rate',
    A: 'Left Output',
    B: 'Right Output',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=snOrmmR5Wfc',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'L6',
    name: 'Mono Chorus',
    Z: 'Wet/Dry',
    X: 'Input',
    Y: 'LFO Rate',
    A: 'X+Chorus',
    B: 'Chorus only',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=snOrmmR5Wfc',
    parameters: [],
    keywords: 'effect',
  },
  {
    code: 'L8',
    name: 'Gate',
    Z: 'Threshold',
    X: 'Left Input',
    Y: 'Right Input',
    A: 'Left Output',
    B: 'Right Output',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=SSGc-mr-Q84',
    parameters: [],
  },
  {
    code: 'M1',
    name: 'Delayed LFO',
    Z: 'LFO Rate',
    X: 'Trigger',
    Y: 'Ramp Time',
    A: 'Output LFO',
    B: 'Output LFO',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=Zq6EXlRmh_g',
    parameters: [],
  },
  {
    code: 'M2',
    name: 'Scaled LFO',
    Z: 'LFO speed',
    X: 'min/max or offset/scale',
    Y: 'min/max or offset/scale',
    A: 'Output LFO',
    B: 'Output LFO',
    extra: [],
    description: ``,
    video: 'https://www.youtube.com/watch?v=NcWLVdAZ50M',
    parameters: [],
  },
];